### ISSUE TITLE
Create a requirements.txt file

### ISSUE THREAD

**Issue by tjnel** [Python-Monthly/Python-Monthly-Website#12]
We should be running the same versions of all of the libraries needed. Lets create a requirements.txt file to ensure we are doing this.

**Comment by archangelic** [comment]
So far, I know we need `pelican` and `Markdown`, anything else that should be included?

Do we need to be specific about the version or should we just say, at least x version?

**Comment by tjnel** [comment]
Looks like @archangelic fixed this thanks!
