### ISSUE TITLE
Add Auto-Title-Casing in new_post.py

### ISSUE THREAD

**Issue by aculler** [Python-Monthly/Python-Monthly-Website#20]
The new_post.py script should automatically title-case the title that is passed to it.

**Comment by kjaymiller** [comment]
While you could use str.proper() it will not properly title case. Is there a module for title casing we can import?

Jay Miller Founder, Host – Productivity in Tech Kjaymiller@gmail.com
On Tue, Oct 18, 2016 at 7:09 AM, Andy Culler notifications@github.com wrote:
The new_post.py script should automatically title-case the title that is passed to it.

**Comment by aculler** [comment]
I'm just planning to use the `string.title()` function. About to push a pull request with the change. Super simple.

**Comment by kjaymiller** [comment]
_Facepalm_ forgot about that. I need to update a few of my repos now! Thanks for the tip!

Jay Miller Founder, Host – Productivity in Tech Kjaymiller@gmail.com
On Tue, Oct 18, 2016 at 7:14 AM, Andy Culler notifications@github.com wrote:
I'm just planning to use the string.title() function. About to push a pull request with the change. Super simple.

**Comment by aculler** [comment]
Hey, that's what collaboration is all about. Happens to me all the time at work during code reviews.

**Comment by aculler** [comment]
This was completed, reviewed and merged by #21. Closing.
