### ISSUE TITLE
create pages directory

### ISSUE THREAD

**Issue by kjaymiller** [Python-Monthly/Python-Monthly-Website#23]
We need to create a directory for static pages.  See http://docs.getpelican.com/en/stable/content.html#pages for more information.

**Comment by archangelic** [comment]
Would creating a folder with a `.leaveme` in it work?

**Comment by kjaymiller** [comment]
I created a test page. so it should be okay.

**Comment by tjnel** [comment]
i have created this directory in another pull request.
