### ISSUE TITLE
Create a Code of Conduct for pythonmonthly

### ISSUE THREAD

**Issue by kjaymiller** [Python-Monthly/Python-Monthly-Website#24]
Establish a Code of Conduct for Python Monthly. Ensure that this document expresses the opinion of the group and encourages and informs others to get involved.

**Comment by archangelic** [comment]
It has been suggested that we base it off the [Django Code of Conduct](https://www.djangoproject.com/conduct/).

**Comment by kjaymiller** [comment]
Was Created by @tjadanel  in pull request #29.
