### ISSUE TITLE
Create section for youtube videos

### ISSUE THREAD

**Issue by kjaymiller** [Python-Monthly/Python-Monthly-Website#3]

**Comment by sgregg85** [comment]
@kjaymiller I was experimenting with implementing this and I think the video from this month's hangout has embedding disabled.

**Comment by kjaymiller** [comment]
I have enabled embedding on the video

**Comment by sgregg85** [comment]
I think we've addressed this by creating them as blog posts as Kenneth suggested, using a Videos category and tag, so they show up in RSS. Anyone else agree that we can close this out

**Comment by kjaymiller** [comment]
Have created a new issue #46 to make Videos easier to find.
