### ISSUE TITLE
Create a scaffolding to get things started.

### ISSUE THREAD

**Issue by danthemanvsqz** [Python-Monthly/Python-Monthly-Website#33]
As a web developer
I need a dev environment to code in
So I can start iterating

Acceptance Criteria:
Dev server that can be run on localhost
Preferably a web framework like Flask, Pyramid or Django. Easy to use batteries included.

**Comment by kjaymiller** [comment]
@danthemanvsqz I'm not sure the issue on this one. Is this a blog post that you would like someone to write, or would you like to look at the framework running the existing site (Pelican)?
