### ISSUE TITLE
Create a Design for the Website

### ISSUE THREAD

**Issue by kjaymiller** [Python-Monthly/Python-Monthly-Website#6]
Come up with a concept for the website design and we can start skinning it.

**Comment by kjaymiller** [comment]
Looking at http://www.pelicanthemes.com/ for a good base theme.

**Comment by kjaymiller** [comment]
## My List of Picks!
- https://github.com/gilsondev/pelican-clean-blog/tree/ea156f8f1741e473bc0ab848b7c8898112d6ffb5
- https://github.com/getpelican/pelican-themes/tree/master/cebong
- https://github.com/porterjamesj/crowsfoot/tree/30509fc0cf6d4c29f2d1d9ec87783340a7158538
- https://github.com/PierrePaul/html5-dopetrope/tree/6796c779663b2797c7a411a776f5167b8b667dfc
- https://github.com/slok/iris/tree/f0e6b87dd8b2d592112b34f0bc674f352d04c1f0
- https://github.com/lazycoder-ru/lazystrap/tree/c9358d8184314bddc6a04adc9ddf6dd001d1f8e0
- https://github.com/molivier/nest/tree/18aa1345f70219c00704848d321daf45c2f50ba7
- https://github.com/kdheepak89/pelican-smoothie/tree/538a3a03281ac641cecd73b420d6d6ec4ebdc6a1
- https://github.com/frankV/twenty-pelican-html5up/tree/53cc173993b358690e8ea00de02154547d5dfdca
- https://github.com/getpelican/pelican-themes/tree/master/zurb-F5-basic

I think we should play the elimination game with these. I'll post pics in the slack channel

**Comment by tjnel** [comment]
Some of the ones l like:
- https://github.com/gilsondev/pelican-clean-blog/tree/ea156f8f1741e473bc0ab848b7c8898112d6ffb5
- https://github.com/PierrePaul/html5-dopetrope/tree/6796c779663b2797c7a411a776f5167b8b667dfc
- https://github.com/molivier/nest/tree/18aa1345f70219c00704848d321daf45c2f50ba7
- https://github.com/frankV/twenty-pelican-html5up/tree/53cc173993b358690e8ea00de02154547d5dfdca

**Comment by sgregg85** [comment]
I like pelican-bootstrap3 because it seems simple, clean and functional and since it's bootstrap, it's responsive.
https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3
And also Gum
https://github.com/getpelican/pelican-themes/tree/master/gum

From Jay's list, I like pelican-smoothie and pelican-clean-blog

**Comment by tjnel** [comment]
Looks like we are all agreeing on the Clean for Pelican Template so far.

**Comment by kjaymiller** [comment]
Works for me. Closing this issue and opening new one.
