### ISSUE TITLE
Site needs to be republished

### ISSUE THREAD

**Issue by possnfiffer** [Python-Monthly/Python-Monthly-Website#69]
![screenshot_20170303-200800](https://cloud.githubusercontent.com/assets/773239/23575634/2f13f10e-004d-11e7-9bc5-73d54331b3d1.png)
The latest article isn't showing up on the website.
I'm not sure how to republish the site so I made this issue.

**Comment by possnfiffer** [comment]
Looks like I need to practice using Pelican http://docs.getpelican.com/en/3.0/tips.html

**Comment by possnfiffer** [comment]
This issue will be resolved once the following PR is in master:
[PR](https://github.com/Python-Monthly/pythonmonthly.github.io/pull/71)

**Comment by sgregg85** [comment]
Issue resolved by PR #71
